version: '2.2'
services:
  syslog1:
    image: bazillasoft/fluentd:1.0.1
    container_name: syslogd1
    privileged: true
    cap_add:
      - SYS_ADMIN
    volumes:
      - /root/fluent/syslog-final.conf:/opt/syslog-ng/etc/syslog-ng.conf
      - /root/fluent/patterndb.xml:/opt/syslog-ng/var/db/patterndb.xml
      - /root/fluent/log4j.xml:/etc/syslog-ng/log4j.xml
      - /root/fluent/td-agent1.conf:/etc/fluent/fluent.conf
      - /root/fluent/td-agent1.conf:/etc/td-agent/td-agent.conf
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    ports:
      - "40001:40001/udp"
      - "40002:40002/udp"
      - "40003:40003/udp"
      - "40004:40004/udp"
      - "24220:24220/tcp"
    networks:
      - olsnet

networks:
  olsnet:
    ipam:
      config:
        - subnet: 172.28.0.0/16
          ip_range: 172.28.0.0/24
          gateway: 172.28.0.255
